name: Deploy Static Site to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy-site:
    name: Deploy site files to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync site to S3
        run: |
          aws s3 sync . s3://aws-image-processor-site \
            --exclude ".git/*" \
            --delete
